# Generated by Django 5.2.7 on 2025-11-07 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detector', '0006_remove_dispositivo_dispositivo_mac_unica_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaz', models.CharField(max_length=64)),
                ('modo', models.CharField(choices=[('pasiva', 'Pasiva'), ('activa', 'Activa'), ('mixta', 'Mixta')], default='pasiva', max_length=16)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('cron', 'Programada'), ('api', 'API / Remota')], default='manual', max_length=16)),
                ('filtro_bpf', models.CharField(blank=True, max_length=255)),
                ('duracion_objetivo', models.PositiveIntegerField(blank=True, help_text='Duración planeada en segundos.', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('capturando', 'Capturando'), ('completada', 'Completada'), ('abortada', 'Abortada'), ('error', 'Error')], default='pendiente', max_length=16)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('total_paquetes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('paquetes_descartados', models.BigIntegerField(default=0)),
                ('ruta_pcap', models.CharField(blank=True, max_length=512)),
                ('hash_pcap', models.CharField(blank=True, max_length=128)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sesión de captura',
                'verbose_name_plural': 'Sesiones de captura',
                'db_table': 'captura_sesion',
                'ordering': ('-inicio',),
            },
        ),
        migrations.CreateModel(
            name='CapturaEstadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts_unicos', models.PositiveIntegerField(default=0)),
                ('puertos_unicos', models.PositiveIntegerField(default=0)),
                ('protocolos_top', models.JSONField(blank=True, default=dict)),
                ('ancho_banda_promedio', models.FloatField(blank=True, help_text='Mbps promedio.', null=True)),
                ('ancho_banda_pico', models.FloatField(blank=True, help_text='Mbps pico.', null=True)),
                ('alertas_generadas', models.PositiveIntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadistica', to='captura.capturasesion')),
            ],
            options={
                'verbose_name': 'Estadística de captura',
                'verbose_name_plural': 'Estadísticas de captura',
                'db_table': 'captura_estadistica',
            },
        ),
        migrations.CreateModel(
            name='CapturaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pcap', 'PCAP'), ('resumen', 'Resumen'), ('otro', 'Otro')], default='pcap', max_length=16)),
                ('ruta', models.CharField(max_length=512)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('hash_archivo', models.CharField(blank=True, max_length=128)),
                ('protegido', models.BooleanField(default=False)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='captura.capturasesion')),
            ],
            options={
                'verbose_name': 'Archivo de captura',
                'verbose_name_plural': 'Archivos de captura',
                'db_table': 'captura_archivo',
                'ordering': ('-creado',),
            },
        ),
        migrations.CreateModel(
            name='CapturaAccionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tcp_syn', 'TCP SYN'), ('udp_probe', 'UDP Probe'), ('custom', 'Payload personalizado'), ('otro', 'Otro')], default='tcp_syn', max_length=16)),
                ('objetivo', models.CharField(max_length=255)),
                ('puerto', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('exitoso', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ejecutada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_activas', to='captura.capturasesion')),
            ],
            options={
                'verbose_name': 'Acción activa de captura',
                'verbose_name_plural': 'Acciones activas de captura',
                'db_table': 'captura_accion_activa',
                'ordering': ('-ejecutada_en',),
            },
        ),
        migrations.CreateModel(
            name='CapturaFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventana_inicio', models.DateTimeField()),
                ('ventana_fin', models.DateTimeField()),
                ('direccion', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ambas', 'Ambas')], default='ambas', max_length=16)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.PositiveIntegerField(blank=True, null=True)),
                ('dst_port', models.PositiveIntegerField(blank=True, null=True)),
                ('src_mac', models.CharField(blank=True, max_length=32)),
                ('dst_mac', models.CharField(blank=True, max_length=32)),
                ('protocolo', models.CharField(max_length=16)),
                ('paquetes', models.BigIntegerField(default=0)),
                ('bytes', models.BigIntegerField(default=0)),
                ('flag_syn', models.BooleanField(default=False)),
                ('flag_fin', models.BooleanField(default=False)),
                ('flag_rst', models.BooleanField(default=False)),
                ('ttl_promedio', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_window_promedio', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_mss', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_opciones', models.CharField(blank=True, max_length=128)),
                ('payload_muestra', models.TextField(blank=True)),
                ('dispositivo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_destino', to='detector.dispositivo')),
                ('dispositivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos_origen', to='detector.dispositivo')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='captura.capturasesion')),
            ],
            options={
                'verbose_name': 'Flujo capturado',
                'verbose_name_plural': 'Flujos capturados',
                'db_table': 'captura_flujo',
                'indexes': [models.Index(fields=['sesion', 'ventana_inicio'], name='captura_flu_sesion__6bf572_idx'), models.Index(fields=['src_ip', 'dst_ip'], name='captura_flu_src_ip_54b127_idx'), models.Index(fields=['protocolo'], name='captura_flu_protoco_ab35ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='FingerprintObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pasivo', 'Pasivo'), ('activo', 'Activo')], default='pasivo', max_length=16)),
                ('sistema_estimado', models.CharField(blank=True, max_length=128)),
                ('version_estimado', models.CharField(blank=True, max_length=128)),
                ('probabilidad', models.FloatField(blank=True, help_text='Valor entre 0 y 1.', null=True)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='detector.dispositivo')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='captura.capturasesion')),
            ],
            options={
                'verbose_name': 'Observación de fingerprint',
                'verbose_name_plural': 'Observaciones de fingerprint',
                'db_table': 'fingerprint_observacion',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['dispositivo', '-timestamp'], name='fingerprint_disposi_ff03da_idx'), models.Index(fields=['metodo'], name='fingerprint_metodo_61b21e_idx')],
            },
        ),
    ]
