# Generated by Django 5.2.7 on 2025-11-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captura', '0002_capturasesion_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturasesion',
            name='modo',
            field=models.CharField(choices=[('pasiva', 'Pasiva')], default='pasiva', max_length=16),
        ),
        migrations.DeleteModel(
            name='CapturaAccionActiva',
        ),
    ]
