# Generated by Django 5.2.7 on 2025-10-20 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('interfaz', models.CharField(max_length=64)),
                ('tipo', models.CharField(choices=[('escaner-activo', 'Escaner activo'), ('captura-pasiva', 'Captura pasiva'), ('mixto', 'Mixto')], max_length=32)),
                ('total_hosts_detectados', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Analisis de red',
                'verbose_name_plural': 'Analisis de redes',
                'db_table': 'analisis_red',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=32, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('primera_vez', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_vez', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('desconocido', 'Desconocido')], default='desconocido', max_length=32)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='DispositivoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(max_length=32)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('dhcp', 'Asignación DHCP'), ('reasignacion', 'Reasignación'), ('manual', 'Cambio manual'), ('otro', 'Otro')], default='otro', max_length=32)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='detector.dispositivo')),
            ],
            options={
                'verbose_name': 'Historial de dispositivo',
                'verbose_name_plural': 'Historiales de dispositivos',
                'db_table': 'dispositivo_historial',
            },
        ),
        migrations.CreateModel(
            name='HostDetectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(blank=True, max_length=32)),
                ('metodo_deteccion', models.CharField(choices=[('arp', 'ARP'), ('ping', 'Ping'), ('nmap', 'Nmap'), ('passive', 'Pasivo'), ('otro', 'Otro')], max_length=32)),
                ('latencia_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('primera_vista', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_vista', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts_detectados', to='detector.analisisred')),
            ],
            options={
                'verbose_name': 'Host detectado',
                'verbose_name_plural': 'Hosts detectados',
                'db_table': 'host_detectado',
            },
        ),
    ]
