# Generated by Django 5.2.7 on 2025-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='mac_aleatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='metodo_identificacion',
            field=models.CharField(choices=[('mac', 'MAC'), ('hostname', 'Hostname'), ('ip', 'IP'), ('manual', 'Manual')], default='mac', max_length=16),
        ),
    ]
