# Generated by Django 5.2.7 on 2025-10-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_dispositivo_mac_aleatoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisred',
            name='duracion_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
