# Generated by Django 5.2.7 on 2025-10-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0003_analisisred_duracion_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='mac',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_aleatoria', False)), fields=('mac',), name='dispositivo_mac_unica_real'),
        ),
    ]
