# Generated by Django 5.2.7 on 2025-10-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_alter_dispositivo_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='es_temporal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='vendor',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
