# Generated by Django 5.2.7 on 2025-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_dispositivo_es_temporal_dispositivo_vendor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispositivo',
            name='dispositivo_mac_unica_real',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='mac',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
