# Generated by Django 5.2.7 on 2025-11-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0006_remove_dispositivo_dispositivo_mac_unica_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='fuente_fingerprint',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultima_fingerprint',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
