# Generated by Django 5.2.7 on 2025-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0007_dispositivo_fuente_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='hostname_fuente',
            field=models.CharField(choices=[('sin_datos', 'Sin datos'), ('detector', 'Detector'), ('captura', 'Captura'), ('manual', 'Manual')], default='sin_datos', max_length=16),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.CharField(choices=[('desconocido', 'Desconocido'), ('pc', 'PC / Notebook'), ('movil', 'Móvil / Tablet'), ('tv', 'Smart TV'), ('iot', 'IoT / Hogar'), ('impresora', 'Impresora / Periférico'), ('router', 'Router / Infraestructura'), ('servidor', 'Servidor / Appliance')], default='desconocido', max_length=16),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_fuente',
            field=models.CharField(choices=[('sin_datos', 'Sin datos'), ('heuristica', 'Heurística'), ('manual', 'Manual')], default='sin_datos', max_length=16),
        ),
    ]
