# Generated by Django 5.2.7 on 2025-11-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_remove_dispositivo_es_temporal_and_metodo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisisred',
            name='tipo',
            field=models.CharField(choices=[('arp_rapido', 'ARP rápido'), ('arp_completo', 'ARP completo'), ('mixto', 'Mixto ARP + fingerprint')], max_length=32),
        ),
    ]
