# Generated by Django 5.2.7 on 2025-10-31 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detector', '0006_remove_dispositivo_dispositivo_mac_unica_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255)),
                ('tipo_scan', models.CharField(choices=[('rapido', 'Rapido (top ports)'), ('tcp-completo', 'TCP completo'), ('tcp-1000', 'TCP primeros 1000')], max_length=32)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=16)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_scanner', to='detector.analisisred')),
            ],
            options={
                'verbose_name': 'Trabajo de escaner',
                'verbose_name_plural': 'Trabajos de escaner',
                'db_table': 'trabajo_scanner',
            },
        ),
        migrations.CreateModel(
            name='PuertoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.PositiveIntegerField()),
                ('protocolo', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=8)),
                ('servicio', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('filtrado', 'Filtrado'), ('cerrado', 'Cerrado')], max_length=16)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='detector.analisisred')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puertos', to='detector.dispositivo')),
                ('host_detectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puertos', to='detector.hostdetectado')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='escaner.trabajoscanner')),
            ],
            options={
                'verbose_name': 'Puerto encontrado',
                'verbose_name_plural': 'Puertos encontrados',
                'db_table': 'puerto_encontrado',
                'indexes': [models.Index(fields=['puerto', 'protocolo'], name='puerto_enco_puerto_4bb6f1_idx')],
            },
        ),
    ]
