# Generated by Django 5.2.7 on 2025-11-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puertoencontrado',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puertoencontrado',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='puertos', to='detector.analisisred'),
        ),
        migrations.AlterField(
            model_name='trabajoscanner',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='trabajos_scanner', to='detector.analisisred'),
        ),
    ]
