# Generated by Django 5.2.7 on 2025-11-02 03:16

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puertoencontrado',
            name='host_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puertoencontrado',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='puertos', to='detector.analisisred'),
        ),
        migrations.AlterField(
            model_name='trabajoscanner',
            name='analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='trabajos_scanner', to='detector.analisisred'),
        ),
        migrations.CreateModel(
            name='PuertoResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField()),
                ('puerto', models.PositiveIntegerField()),
                ('protocolo', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], max_length=8)),
                ('servicio', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('filtrado', 'Filtrado'), ('cerrado', 'Cerrado')], max_length=16)),
                ('primera_detectado', models.DateTimeField(default=timezone.now)),
                ('ultima_detectado', models.DateTimeField(default=timezone.now)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='puertos_resumen', to='detector.dispositivo')),
                ('ultima_trabajo', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='puertos_resumen', to='escaner.trabajoscanner')),
            ],
            options={
                'verbose_name': 'Puerto resumido',
                'verbose_name_plural': 'Puertos resumidos',
                'db_table': 'puerto_resumen',
            },
        ),
        migrations.AddIndex(
            model_name='puertoresumen',
            index=models.Index(fields=['host_ip', 'puerto', 'protocolo'], name='puerto_resumen_host_ip_idx'),
        ),
    ]
