# Generated by Django 5.2.7 on 2025-11-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escaner', '0002_puertoencontrado_host_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajoscanner',
            name='tipo_scan',
            field=models.CharField(choices=[('rapido', 'Rápido (top ports)'), ('tcp-completo', 'TCP completo'), ('tcp-1000', 'TCP primeros 1000'), ('personalizado', 'Personalizado')], max_length=32),
        ),
    ]
