# Generated by Django 5.2.7 on 2025-11-03 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escaner', '0003_alter_trabajoscanner_tipo_scan'),
    ]

    operations = []
