# Generated by Django 5.2.7 on 2025-10-19 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaz', models.CharField(max_length=64)),
                ('ip_local', models.GenericIPAddressField()),
                ('cidr', models.PositiveSmallIntegerField()),
                ('mac', models.CharField(max_length=32)),
                ('hostname', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Agente local',
                'verbose_name_plural': 'Agentes locales',
                'db_table': 'agente_local',
            },
        ),
    ]
