# Generated by Django 5.2.7 on 2025-10-20 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentelocal',
            old_name='last_update',
            new_name='ultima_actualizacion',
        ),
    ]
