# Generated by Django 5.2.7 on 2025-10-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0002_rename_last_update_agentelocal_ultima_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentelocal',
            name='mac',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
