# Generated by Django 5.2.7 on 2025-11-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0003_alter_agentelocal_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentelocal',
            name='mac',
            field=models.CharField(max_length=32),
        ),
    ]
