# Generated by Django 5.2.7 on 2025-11-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0004_alter_agentelocal_mac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentelocal',
            old_name='notas',
            new_name='ubicacion',
        ),
        migrations.AlterField(
            model_name='agentelocal',
            name='mac',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='agentelocal',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
