# Generated by Django 5.2.7 on 2025-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0005_rename_notas_agentelocal_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentelocal',
            name='mac',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='agentelocal',
            constraint=models.UniqueConstraint(fields=('mac', 'ubicacion'), name='agente_mac_ubicacion_unique'),
        ),
    ]
