# Generated by Django 5.2.7 on 2025-11-12 17:05

from django.db import migrations, models


def migrate_slugs(apps, schema_editor):
    AgenteLocal = apps.get_model("agente", "AgenteLocal")
    for agente in AgenteLocal.objects.all():
        agente.ubicacion_slug = (agente.ubicacion or "").strip().lower()
        agente.save(update_fields=["ubicacion_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0006_alter_agentelocal_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentelocal',
            name='ubicacion_slug',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RemoveConstraint(
            model_name='agentelocal',
            name='agente_mac_ubicacion_unique',
        ),
        migrations.RunPython(migrate_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='agentelocal',
            constraint=models.UniqueConstraint(fields=('mac', 'ubicacion_slug'), name='agente_mac_ubicacion_unique'),
        ),
    ]
