# Generated by Django 5.2.7 on 2025-11-07 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detector', '0006_remove_dispositivo_dispositivo_mac_unica_real_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeuristicaRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('modulo_objetivo', models.CharField(choices=[('captura', 'Captura'), ('detector', 'Detección de hosts'), ('escaner', 'Escáner de puertos'), ('global', 'Global')], default='captura', max_length=16)),
                ('tipo', models.CharField(choices=[('comportamiento', 'Comportamiento'), ('firma', 'Firma'), ('fingerprinting', 'Fingerprinting'), ('otro', 'Otro')], default='comportamiento', max_length=32)),
                ('descripcion', models.TextField(blank=True)),
                ('severidad_por_defecto', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=16)),
                ('parametros', models.JSONField(blank=True, default=dict, help_text='Configuración dinámica de la regla.')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla de heurística',
                'verbose_name_plural': 'Reglas de heurística',
                'db_table': 'heuristica_regla',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='HeuristicaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=16)),
                ('descripcion', models.TextField()),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('notificado', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_heuristica', to='detector.analisisred')),
            ],
            options={
                'verbose_name': 'Evento heurístico',
                'verbose_name_plural': 'Eventos heurísticos',
                'db_table': 'heuristica_evento',
                'ordering': ('-ts',),
            },
        ),
    ]
