# Generated by Django 5.2.7 on 2025-11-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analitica', '0001_initial'),
        ('captura', '0001_initial'),
        ('detector', '0006_remove_dispositivo_dispositivo_mac_unica_real_and_more'),
        ('escaner', '0004_rename_puerto_resu_host_ip_1470d5_idx_puerto_resumen_host_ip_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='heuristicaevento',
            name='captura_flujo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_heuristica', to='captura.capturaflujo'),
        ),
        migrations.AddField(
            model_name='heuristicaevento',
            name='captura_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_heuristica', to='captura.capturasesion'),
        ),
        migrations.AddField(
            model_name='heuristicaevento',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_heuristica', to='detector.dispositivo'),
        ),
        migrations.AddField(
            model_name='heuristicaevento',
            name='puerto_resumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_heuristica', to='escaner.puertoresumen'),
        ),
        migrations.AddField(
            model_name='heuristicaevento',
            name='regla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='analitica.heuristicaregla'),
        ),
        migrations.AddIndex(
            model_name='heuristicaevento',
            index=models.Index(fields=['ts'], name='heuristica__ts_610405_idx'),
        ),
        migrations.AddIndex(
            model_name='heuristicaevento',
            index=models.Index(fields=['severidad'], name='heuristica__severid_1730b6_idx'),
        ),
    ]
